version: '3.3'
services:
  postgress:
    image: postgres:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=veterinary
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data